workflows:
  version: 2
  build-deploy:
    jobs:
      - build

version: 2
jobs:
  build:
    working_directory: ~/kgrid-python-runtime
    docker:
      - image: circleci/python:3.8.6
    steps:
      - checkout  # checkout source code to working directory
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            pwd
            export PYTHONPATH=~/kgrid-python-runtime/tests
            cd tests
            python3 -m unittest discover
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/